const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('zh-HK',{style:'currency',currency:'HKD',maximumFractionDigits:2}).format(n||0), short=n=>n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:money(n), fmt=d=>d?new Intl.DateTimeFormat('zh-HK',{year:'numeric',month:'short',day:'numeric'}).format(new Date(d+'T00:00:00')):'—',fmtMonth=m=>new Intl.DateTimeFormat('zh-HK',{year:'numeric',month:'long'}).format(new Date(m+'-01T00:00:00'));
let data=null,history={},view='home',filter='全部',query='';
async function load(){try{const [c,h]=await Promise.all([fetch(`data/current.json?t=${Date.now()}`),fetch(`data/history.json?t=${Date.now()}`)]);data=await c.json();history=await h.json();$('#status').textContent=`已同步 · ${new Date(data.syncedAt).toLocaleString('zh-HK')}`;setupMonths();render()}catch(e){$('#status').textContent='暫時未能讀取資料，請稍後再試';$('#content').innerHTML='<div class="empty">同步資料準備中…</div>'}}
function setupMonths(){const el=$('#month'),months=Object.keys(history).sort().reverse();el.innerHTML=months.map(m=>`<option value="${m}" ${m===data.month?'selected':''}>${fmtMonth(m)}</option>`).join('');el.onchange=()=>{data=history[el.value];render()}}
function sums(){const t=data.transactions||[],income=t.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense=t.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0),assets=(data.deposits||[]).reduce((s,x)=>s+x.principal,0);return{income,expense,assets,balance:income-expense}}
function txRow(x){return `<div class="tx ${x.type}"><i>${x.type==='income'?'↗':'✿'}</i><span><strong>${x.name}</strong><p>${x.category}${x.due?' · '+x.due:''}</p></span><b>${x.type==='income'?'+':'−'}${money(x.amount)}</b></div>`}
function render(){if(!data)return;$('#title').textContent=view==='home'?'理財總覽':view==='transactions'?'每月收支':'定期資產';document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));view==='home'?home():view==='transactions'?transactions():deposits()}
function home(){const s=sums(),tx=data.transactions||[],cats={};tx.filter(x=>x.type==='expense').forEach(x=>cats[x.category]=(cats[x.category]||0)+x.amount);const list=Object.entries(cats).sort((a,b)=>b[1]-a[1]),colors=['#a64663','#df8da3','#89a599','#d2b36c','#bea0bb'];let n=0,stops=list.map(([,v],i)=>{const a=n;n+=v/s.expense*100;return`${colors[i%colors.length]} ${a}% ${n}%`}).join(',');const upcoming=[...(data.deposits||[])].filter(x=>x.maturityDate).sort((a,b)=>a.maturityDate.localeCompare(b.maturityDate)).slice(0,3);$('#content').innerHTML=`<section class="hero"><div><small>${fmtMonth(data.month)}可用結餘</small><h2>${money(s.balance)}</h2><p>收入 ${money(s.income)} · 支出 ${money(s.expense)}</p></div><div class="ring">${s.income?Math.round(s.expense/s.income*100):100}%</div></section><section class="metrics"><div class="metric"><span>每月總收入</span><strong>${money(s.income)}</strong><small>包括定期平均 ${money(data.fixedMonthlyIncome)}</small></div><div class="metric"><span>本月支出</span><strong>${money(s.expense)}</strong><small>${tx.filter(x=>x.type==='expense').length} 個項目</small></div><div class="metric"><span>總資產</span><strong>${money(s.assets)}</strong><small>定期及投資本金</small></div></section><section class="grid"><article class="panel"><span class="kicker">LATEST</span><h2>今月項目</h2>${tx.slice(0,6).map(txRow).join('')}</article><div><article class="panel"><span class="kicker">SPENDING MIX</span><h2>支出分佈</h2><div class="mix"><div class="donut" style="background:conic-gradient(${stops})"><span>${money(s.expense)}</span></div><div class="legend">${list.map(([k,v],i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${k}</span><b>${Math.round(v/s.expense*100)}%</b></div>`).join('')}</div></div></article><article class="panel" style="margin-top:16px"><span class="kicker">MATURITY</span><h2>即將到期</h2><div class="maturity">${upcoming.map(d=>`<div><time>${fmt(d.maturityDate)}</time><span><strong>${d.bank}</strong><small>${d.rate}</small></span><b>${short(d.principal)}</b></div>`).join('')}</div></article></div></section>`}
function transactions(){const all=data.transactions||[],cats=['全部',...new Set(all.map(x=>x.category))],shown=all.filter(x=>(filter==='全部'||x.category===filter)&&(`${x.name}${x.category}${x.due||''}`.toLowerCase().includes(query.toLowerCase())));$('#content').innerHTML=`<div class="toolbar"><input id="search" placeholder="搜尋項目、分類或到期日" value="${query}"></div><div class="chips">${cats.map(c=>`<button class="${filter===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><article class="panel">${shown.length?shown.map(txRow).join(''):'<div class="empty">搵唔到符合條件嘅項目</div>'}</article>`;$('#search').oninput=e=>{query=e.target.value;transactions()};document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;transactions()})}
function monthly(d){if(d.status!=='active'||!d.startDate||!d.maturityDate)return 0;return d.interest/Math.max(1,(new Date(d.maturityDate)-new Date(d.startDate))/2629800000)}
function deposits(){const ds=[...(data.deposits||[])].sort((a,b)=>(a.maturityDate||'9999').localeCompare(b.maturityDate||'9999')||a.bank.localeCompare(b.bank));$('#content').innerHTML=`<section class="metrics"><div class="metric"><span>資產本金</span><strong>${money(ds.reduce((s,d)=>s+d.principal,0))}</strong></div><div class="metric"><span>預計利息／回報</span><strong>${money(ds.reduce((s,d)=>s+d.interest,0))}</strong></div><div class="metric"><span>今月定期平均收入</span><strong>${money(data.fixedMonthlyIncome)}</strong></div></section><section class="deposits">${ds.map(d=>`<article class="deposit-card"><div class="deposit-top"><b class="bank">${d.bank[0]}</b><span><strong>${d.bank}</strong><small>${d.status==='active'?'定期存款':'投資資產'}</small></span><i>${d.rate||'—'}</i></div><p>本金</p><h3>${money(d.principal)}</h3><div class="meta"><span><small>${d.maturityDate?'到期日':'更新日'}</small>${fmt(d.maturityDate||d.startDate)}</span><span><small>${d.status==='active'?'每月平均':'預計回報'}</small>${d.status==='active'?money(monthly(d)):money(d.interest)}</span></div></article>`).join('')}</section>`}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{view=b.dataset.view;scrollTo({top:0,behavior:'smooth'});render()});$('#refresh').onclick=load;load();
